const languages = {
    en: {
      "title": "Momentum",
      "profile-name": "HELLO",
      "сhoose-language": "Choose language",
      "image-source": "Image source",
      "show-blocks": "Customize your dashboard",
      "time": "Time",
      "date": "Date",
      "player": "Player",
      "greeting": "Greeting",
      "quote": "Quote",
      "weather": "Weather",
      "wind": "Wind speed: ",
      "humidity": "Humidity: ",
      "todo": "Todo",
      "task1": "Feed the cat",
      "task2": "Call Elon Musk",
      "empty-tasks": "All tasks completed. There are no new tasks",
      "add-task": "Add task",
      "todo-list-button": "TODO",
    },
    ru: {
      "title": "Моменты",
      "profile-name": "ПРИВЕТ!!",
      "сhoose-language": "Выберите язык",
      "image-source": "Изображение для фона",
      "show-blocks": "Показать / скрыть блоки",
      "time": "Время",
      "date": "Дата",
      "player": "Плеер",
      "greeting": "Приветствие",
      "quote": "Цитаты",
      "wind": "Скорость ветра",
      "humidity": "Влажность",
      "weather": "Погода",
      "todo": "Список дел",
      "task1": "Покормить кота",
      "task2": "Позвонить Илону Маску",
      "empty-tasks": "Все задания выполнены. Новых задач нет",
      "add-task": "Добавить",
      "todo-list-button": "Дела",
    },
  };

export default languages;